---
- name: Load OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - ../vars/{{ ansible_distribution }}.yml
    - ../vars/{{ ansible_os_family }}.yml

- name: set timezone
  timezone:
    name: "{{ timezone }}"
  notify:
    - restart cron
    - restart dependent services