- name: Restart cron
  ansible.builtin.service:
    name: "{{ timezone_cron_daemon }}"
    state: restarted
    enabled: true

- name: Restart dependent services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ timezone_services_restart }}"
  when: timezone_services_restart is defined and timezone_services_restart
